version: '3.3'


services:

  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - db_value:/app/db/

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


volumes:
  db_value: