# Generated by Django 4.2 on 2024-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_group_students',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Students In Group'),
        ),
        migrations.AddField(
            model_name='course',
            name='min_group_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Min Students In Group'),
        ),
    ]
