# Generated by Django 4.2 on 2024-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_max_group_students_course_min_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_group_students',
            field=models.PositiveIntegerField(verbose_name='Max Students In Group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_group_students',
            field=models.PositiveIntegerField(verbose_name='Min Students In Group'),
        ),
    ]
